### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by robbertgroen** [GeraYoga/CheckOwner#1]
Hello GeraYoga,

I really like the idea of being able to identify the owner of any given object in an Unturned server. I have added your plugin to our server.

As a server Admin I'm currently only able to use /whois on my own objects. Is there something I need to do before I can use /whois on objects owned by other players?

Thanks in advance for your reply!

Kind regards,
Robbert (HarmlessEppo on Steam)

ps. I would be happy to test things if needed.

**Comment by GeraYoga** [comment]
Fixed https://github.com/GeraYoga/CheckOwner/releases/download/ReleasePlugin/GY.CheckOwner.dll

**Comment by robbertgroen** [comment]
Thanks!

Works great now.
