### ISSUE TITLE
For your consideration

### ISSUE THREAD

**Issue by robbertgroen** [GeraYoga/CheckOwner#2]
Hello GeraYoga,

What do you think about my suggestion below?

The /whois command shows only one name of the player. Would it be possible to show both the Steam name AND the Character name? (the in-game name)

Many players use different names for on Steam / in Unturned.

Looking forward to your reply.

Kind regards,
Robbert

**Comment by GeraYoga** [comment]
Hi, robbertgroen.

When a player is online, it is better to use Character name, so it will be easier to find it in the list of players, but I will think about your idea and maybe add it.

**Comment by robbertgroen** [comment]
Hi GeraYoda,

Thanks for considering it. I'll keep checking the plugin in the future.

Great to have it working like it is already, happy server crew here! 

Kind regards,
Robbert
