### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by robbertgroen** [GeraYoga/CheckOwner#3]
Dear reader,

We have been using your plugin on our Unturned servers with great pleasure. Thank you for that.

Somehow the plugin stopped working correctly after the last Unturned update.

Is this something you can fix? Or is this something wrong on my servers?

Thank you in advance for your reply!

Kind regards,
Robbert

**Comment by tilted-dev** [comment]
All plugins are stored in the new repository - [Click](https://github.com/GY-Plugins)

**Comment by GeraYoga** [comment]
https://github.com/GY-Plugins/GY.CheckOwner/releases/tag/v.1.0 - new version.
